version: '3'

services:
  app1:
    build: .
    container_name: express-app1-container
    restart: always
    ports:
      - 3000:3000

  app2:
    build: .
    container_name: express-app2-container
    restart: always
    ports:
      - 3001:3000
    environment:
      - APP_PORT=3000

  nginx:
    image: nginx:stable-alpine
    container_name: ReverseProxy-Loadbalancer-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
